#!/bin/bash
mysql -u cod_reader -h www.crystallography.net cod -e \
    'select count(*) from data where status is null or status != "retracted"' -N \
    | head -n 1 \
    | sed 's/[^0-9]//' \
    | tm1638-write
