#!/usr/bin/perl

use strict;
use warnings;

$| = 1; # autoflushing STDOUT

while( <> ) {
    my @words = split;
    for( @words ) {
         s/[^a-zA-Z0-9]//g;
         next if !$_;
         if( length() < 8 ) {
             print $_, "\n";
             sleep 1;
         } else {
             while( length() >= 8 ) {
                 my $txt = substr( $_, 0, 8 );
                 print $txt, "\n";
                 $_ = substr( $_, 1 );
                 sleep 1;
             }
         }
    }
    sleep 1;
}

print "\n";
